version: '3.8'
name: pipeline-sus

services:
  postgres-saude:
    image: postgres:17
    container_name: postgres-saude
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata_saude:/var/lib/postgresql/data
    networks:
      - rede-saude

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-saude
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres-saude
    networks:
      - rede-saude

networks:
  rede-saude:
    driver: bridge

volumes:
  pgdata_saude: